project:
  type: website
  output-dir: docs
  
website:
  title: "Hydrology Tools"
  navbar:
    left:
      - href: index.qmd
        text: Intro
      - projects.qmd
      - packages.qmd
      - about.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/alonso-arriagada
      - icon: github
        href: https://github.com/Alobondo/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Alonso Arriagada"

format:
  html:
    theme: minty
    toc: true
    
editor: source

